// Automatically generated by astro-icon
// 5934ed349864f53659e8791b42a3fa75479c1548e1dc900ff756e398d11545ee

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "envelope"
		| "github"
		| "linkedin"
		| "newspaper"
		| "twitter-x";
}